[project]
name = "book-scraper-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "pyinputplus>=0.2.12",
    "regex>=2025.7.31",
    "requests>=2.32.4",
]
